name: "build pipeline for web release"

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: npm install
      # - name: Run tests
      # - run: npm test
      - name: Build file
        run: npm run build

      # copy file for netlify.toml
      - name: Copy build settings to build folder
        run: cp netlify.toml build/

      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
  
      - name: Netlify Deploy
        # uses: jsmrcaga/action-netlify-deploy@v1.7.1
  
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          REACT_APP_GOOGLE_MEASUREMENT_ID: ${{ secrets.REACT_APP_GOOGLE_MEASUREMENT_ID}}
        run: netlify deploy --prod

      # # deploy application to netlify
      # - name: Deploy production to Netlify
      #   uses: South-Paw/action-netlify-deploy@v1.2.0
      #   env:
      #     REACT_APP_GOOGLE_MEASUREMENT_ID: ${{ secrets.REACT_APP_GOOGLE_MEASUREMENT_ID}}
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}

      #     build-dir: "./build"
      #     comment-on-commit: true
